modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="the"
version="1.0.3-build005"
displayName="the"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="http://mcbbs.net/thread-945911-1-1.html"
authors="actinatoratium"
description='''
minecraft mod
'''

[[dependencies.the]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"

[[dependencies.the]]
    modId="forge"
    mandatory=true
    versionRange="[28.2.3]"
    ordering="NONE"
    side="BOTH"

[[dependencies.the]]
    modId="mcreator_link"
    mandatory=false
    ordering="NONE"
    side="BOTH"

